FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/collab-server/package*.json ./apps/collab-server/
COPY packages/db/package*.json ./packages/db/

RUN npm install

COPY apps/collab-server ./apps/collab-server
COPY packages/db ./packages/db

EXPOSE 1234

CMD ["npm", "run", "start", "--workspace=collab-server"]